//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuiTche.WEB.MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TuiTcheEntities : DbContext
    {
        public TuiTcheEntities()
            : base("name=TuiTcheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compartilhar> Compartilhar { get; set; }
        public virtual DbSet<Curtir> Curtir { get; set; }
        public virtual DbSet<Hashtag> Hashtag { get; set; }
        public virtual DbSet<PalavraGauderia> PalavraGauderia { get; set; }
        public virtual DbSet<Pontuacao> Pontuacao { get; set; }
        public virtual DbSet<Publicacao> Publicacao { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
